### ISSUE TITLE
The password is stored as plain text in RAM

### ISSUE THREAD

**Issue by pepa65** [raymontag/kppy#16]
I was thinking about the warning given in the readme, "the password is saved as plain text in RAM". Is it possible and not too costly to store the password encrypted in RAM and when applying it decrypt it on the fly?

**Comment by raymontag** [comment]
Of course this is possible but think about these two considerations why I did this not:

1. Python does not allow to overwrite strings in memory. Instead, editing a string does create a new str-object in memory. Due to this, the plaintext would still reside in memory.
2. What is the threat model you are thinking about? Do get access to the RAM, the attacker needs access to the physical RAM or needs access to your system. In the former case, the attacker can investigate your RAM by forensic methods, thus is able to find the stored encryption key. In the latter case, the attacker could use other methods to get your password, e.g. a key logger. And the 1st point still holds.

I hope this clarifies my decision.

By the way, the 1st point is the reason why I want to reimplement this project in Rust because it would allow to store critical data in memory only as long as needed. If I would find the time for this...
